server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: delivery
          uri: http://localhost:9002
          predicates:
            - Path=/delivery/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery/(?<path>.*), /$\{path}
        - id: order
          uri: http://localhost:9001/
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/order/(?<path>.*), /$\{path}
        - id: kitchen
          uri: http://localhost:9003/
          predicates:
            - Path=/kitchen/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/kitchen/(?<path>.*), /$\{path}

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000
