package ru.liga.orderservice.entity;

public enum Status {
    CUSTOMER_CREATED, CUSTOMER_PAID, CUSTOMER_CANCELLED,
    KITCHEN_ACCEPTED, KITCHEN_DENIED, KITCHEN_PREPARING, KITCHEN_REFUNDED,
    DELIVERY_PENDING, DELIVERY_PICKING, DELIVERY_DENIED, DELIVERY_DELIVERING, DELIVERY_REFUNDED, DELIVERY_COMPLETE
}
